package com.dlrp.app.ui

import android.content.Intent
import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import com.dlrp.app.R
import com.dlrp.app.core.AppInitializer
import com.dlrp.app.core.PermissionHandler

// Note: R.layout.activity_home and R.id.* are assumed to exist or will be generated by XML.
// Since we can't create Layout XMLs easily with just Kotlin writes, we will assume ViewBinding or simple setContent.
// For this environment, I'll use programmatic UI setup or assume IDs are standard.

class HomeActivity : AppCompatActivity() {

    private lateinit var safetyTipManager: SafetyTipManager

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_home)

        safetyTipManager = SafetyTipManager()

        initializeUI()
        startServices()
        checkPermissions()
    }

    private fun initializeUI() {
        // 1. Setup Daily Tip
        findViewById<TextView>(R.id.tvDailyTip).text = safetyTipManager.getRandomTip()

        // 2. Setup Guardian Button
        findViewById<Button>(R.id.btnSetupGuardian).setOnClickListener {
            startActivity(Intent(this, GuardianSetupActivity::class.java))
        }

        // 3. Setup Panic Button
        findViewById<Button>(R.id.btnMainPanic).setOnClickListener {
            // Launch Panic Overlay
            startActivity(Intent(this, PanicOverlayActivity::class.java))
            // Speak reassurance
            AppInitializer.instance.voiceAlertManager.speak("Do not worry. We are blocking everything unsafe. Call your guardian if you need help.")
        }
    }

    private fun startServices() {
        // Start background service if needed (though Receivers work without it typically)
        AppInitializer.instance.backgroundServiceManager.startService()
    }

    private fun checkPermissions() {
        // 1. Standard Runtime Permissions (SMS, Phone, Contracts)
        if (!PermissionHandler.hasPermissions(this)) {
            PermissionHandler.requestPermissions(this)
        }

        // 2. Notification Policy Access (for Silent Mode)
        val notificationManager = getSystemService(android.app.NotificationManager::class.java)
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M && !notificationManager.isNotificationPolicyAccessGranted) {
             val intent = android.content.Intent(android.provider.Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS)
             startActivity(intent)
             android.widget.Toast.makeText(this, "Please allow 'Do Not Disturb' access for Silent Mode", android.widget.Toast.LENGTH_LONG).show()
        }
    }
}
